name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  try-handle-multi-lines:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: make echo COMMIT_MESSAGE="${COMMIT_MESSAGE[0]}"
      env:
        COMMIT_MESSAGE: "${{ github.event.head_commit.message }}"
