name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  try-handle-multi-lines:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: echo ${{ github.event.head_commit.message }}
